name: XcraftGate
main: de.xcraft.engelier.XcraftGate.XcraftGate
version: 0.8 
author: Engelier
commands:
  gate:
    description: Modify Teleporters
    usage: /<command> help
    permission: XcraftGate.gate
  gworld:
    description: Manage Worlds
    usage: /<command> help
    permission: XcraftGate.world