name: XcraftGate
main: de.xcraft.engelier.XcraftGate.XcraftGate
version: 0.4
author: Engelier
commands:
  gate:
    description: Modify Teleporters
    usage: /<command> help
  gworld:
    description: Manage Worlds
    usage: /<command> help